[project]
name = "bday-tools"
version = "0.1.0"
authors = [
    {name = "Florian Jackisch", email = "florian.jackisch@gmail.com"}
]
description = "Add your description here"
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "segno>=1.6.6",
]
